version: '3.8'

services:
  # NestJS 应用服务
  app:
    build: . # 使用当前目录的 Dockerfile 构建镜像
    container_name: nestai # 容器名称
    ports:
      - '3000:3000' # 映射主机 3000 端口到容器 3000 端口
    depends_on:
      - mongodb # 确保 MongoDB 先启动
    networks:
      - app-network

  # MongoDB 数据库服务
  mongodb:
    image: mongo:6.0 # 使用官方 MongoDB 镜像
    ports:
      - '27017:27017' # 可选：映射主机端口（仅开发时需要）
    volumes:
      - mongo-data:/data/db # 数据持久化
    networks:
      - app-network

# 定义网络和数据卷
volumes:
  mongo-data: # MongoDB 数据持久化卷

networks:
  app-network: # 自定义网络，使服务可通过服务名通信
    driver: bridge

